"""
test_platinum_tier.py - Platinum Tier Demo Flow Test

This script tests the Platinum Tier end-to-end flow:
1. Simulate Cloud creating a draft
2. Sync to Local
3. Human approval (simulated)
4. Local orchestrator executes
5. Sync completion back to Cloud

Usage:
    python test_platinum_tier.py --vault AI_Employee_Vault
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def test_cloud_draft_creation(vault: Path) -> bool:
    """Test 1: Simulate Cloud creating an email draft."""
    print("\n" + "="*60)
    print("TEST 1: Cloud Draft Creation")
    print("="*60)
    
    drafts_folder = vault / "Cloud" / "Drafts" / "Email"
    drafts_folder.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    draft_file = drafts_folder / f"TEST_DRAFT_REPLY_{timestamp}.md"
    
    content = f"""---
action: send_email
to: test@example.com
subject: Re: Test Email from Platinum Tier
created: {datetime.now(timezone.utc).isoformat()}
priority: high
cloud_draft: true
requires_local_approval: true
---

## Draft Reply (Cloud Generated - Platinum Tier Test)

Dear Test Sender,

This is a test email reply generated by the Cloud Agent as part of the Platinum Tier demo.

**Test Details:**
- Draft created: {datetime.now().isoformat()}
- Priority: High
- Action Required: Local approval and send

This demonstrates the Cloud → Local handoff workflow.

Best regards,
AI Employee (Cloud Agent)

---

## Processing Notes

- Generated by: Cloud Agent (Platinum Tier Test)
- Requires: Local approval before sending
- Sync: Will appear in Local/Pending_Approval/ after Git sync
- Test: This is an automated test file
"""
    
    draft_file.write_text(content, encoding="utf-8")
    print(f"  ✓ Cloud draft created: {draft_file.name}")
    
    # Create approval signal
    updates_folder = vault / "Cloud" / "Updates"
    updates_folder.mkdir(parents=True, exist_ok=True)
    
    signal_file = updates_folder / f"TEST_APPROVAL_SIGNAL_{timestamp}.md"
    signal_content = f"""---
type: approval_signal
source: test_platinum_tier
draft_file: {draft_file.name}
action_type: send_email
priority: high
created: {datetime.now(timezone.utc).isoformat()}
---

## Test Approval Signal

This is a test signal from the Platinum Tier test script.

**Draft:** `{draft_file.name}`
**Action:** Send test email
**Priority:** High

## Local Action Required

1. Review draft in Local/Pending_Approval/
2. If approved, move to Local/Approved/
3. Local Orchestrator will execute
"""
    
    signal_file.write_text(signal_content, encoding="utf-8")
    print(f"  ✓ Approval signal created: {signal_file.name}")
    
    return True


def test_sync_to_local(vault: Path) -> bool:
    """Test 2: Simulate Git sync copying drafts to Local."""
    print("\n" + "="*60)
    print("TEST 2: Sync Cloud Drafts to Local")
    print("="*60)
    
    cloud_drafts = vault / "Cloud" / "Drafts" / "Email"
    local_pending = vault / "Local" / "Pending_Approval"
    local_pending.mkdir(parents=True, exist_ok=True)
    
    copied = 0
    for draft in cloud_drafts.glob("TEST_DRAFT_*.md"):
        dest = local_pending / draft.name
        dest.write_text(draft.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"  → Synced: {draft.name}")
        copied += 1
    
    if copied > 0:
        print(f"  ✓ Synced {copied} draft(s) to Local/Pending_Approval/")
        return True
    else:
        print("  ⚠ No test drafts found to sync")
        return False


def test_human_approval(vault: Path) -> bool:
    """Test 3: Simulate human approval (move to Approved)."""
    print("\n" + "="*60)
    print("TEST 3: Human Approval Simulation")
    print("="*60)
    
    local_pending = vault / "Local" / "Pending_Approval"
    local_approved = vault / "Local" / "Approved"
    local_approved.mkdir(parents=True, exist_ok=True)
    
    approved = 0
    for draft in local_pending.glob("TEST_DRAFT_*.md"):
        dest = local_approved / draft.name
        draft.rename(dest)
        print(f"  → Approved: {draft.name}")
        approved += 1
    
    if approved > 0:
        print(f"  ✓ Approved {approved} file(s) - moved to Local/Approved/")
        return True
    else:
        print("  ⚠ No test drafts found in Pending_Approval")
        return False


def test_orchestrator_execution(vault: Path) -> bool:
    """Test 4: Simulate orchestrator executing approved actions."""
    print("\n" + "="*60)
    print("TEST 4: Local Orchestrator Execution")
    print("="*60)
    
    local_approved = vault / "Local" / "Approved"
    local_done = vault / "Local" / "Done"
    local_done.mkdir(parents=True, exist_ok=True)
    
    executed = 0
    for approved_file in local_approved.glob("TEST_DRAFT_*.md"):
        # Read and verify it's a test file
        content = approved_file.read_text(encoding="utf-8")
        if "Test Email from Platinum Tier" in content:
            # Move to Done (simulating execution)
            dest = local_done / approved_file.name
            approved_file.rename(dest)
            print(f"  → Executed: {approved_file.name}")
            executed += 1
    
    if executed > 0:
        print(f"  ✓ Executed {executed} action(s) - moved to Local/Done/")
        return True
    else:
        print("  ⚠ No test approvals found to execute")
        return False


def test_audit_sync(vault: Path) -> bool:
    """Test 5: Simulate syncing completion back to Cloud."""
    print("\n" + "="*60)
    print("TEST 5: Audit Trail Sync to Cloud")
    print("="*60)
    
    local_done = vault / "Local" / "Done"
    cloud_audit = vault / "Cloud" / "Audit"
    cloud_audit.mkdir(parents=True, exist_ok=True)
    
    synced = 0
    for done_file in local_done.glob("TEST_DRAFT_*.md"):
        dest = cloud_audit / done_file.name
        dest.write_text(done_file.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"  → Synced: {done_file.name}")
        synced += 1
    
    if synced > 0:
        print(f"  ✓ Synced {synced} completed action(s) to Cloud/Audit/")
        return True
    else:
        print("  ⚠ No completed actions to sync")
        return False


def test_security_boundaries(vault: Path) -> bool:
    """Test 6: Verify security boundaries (secrets don't sync)."""
    print("\n" + "="*60)
    print("TEST 6: Security Boundaries Verification")
    print("="*60)
    
    security_checks = {
        ".env": vault / ".env",
        "auth_info/": vault.parent / "whatsapp-baileys" / "auth_info",
        "twitter_cookies": vault / "Logs" / ".twitter_cookies.json",
        "Local/Pending_Approval/": vault / "Local" / "Pending_Approval",
        "Local/Approved/": vault / "Local" / "Approved",
    }
    
    all_secure = True
    for name, path in security_checks.items():
        if path.exists():
            print(f"  ✓ {name} exists (should NOT sync to Cloud)")
        else:
            print(f"  ⚠ {name} not found")
    
    # Check .gitignore
    gitignore = vault.parent / ".gitignore"
    if gitignore.exists():
        content = gitignore.read_text()
        if "Local/Pending_Approval/" in content and "auth_info" in content:
            print(f"  ✓ .gitignore properly configured")
        else:
            print(f"  ⚠ .gitignore may be missing security rules")
            all_secure = False
    
    return all_secure


def run_all_tests(vault: Path):
    """Run all Platinum Tier tests."""
    print("\n" + "="*70)
    print("  PLATINUM TIER - END-TO-END DEMO FLOW TEST")
    print("="*70)
    print(f"\nVault Path: {vault}")
    print(f"Timestamp:  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    results = {}
    
    # Run tests in order
    results["cloud_draft"] = test_cloud_draft_creation(vault)
    results["sync_to_local"] = test_sync_to_local(vault)
    results["human_approval"] = test_human_approval(vault)
    results["orchestrator"] = test_orchestrator_execution(vault)
    results["audit_sync"] = test_audit_sync(vault)
    results["security"] = test_security_boundaries(vault)
    
    # Summary
    print("\n" + "="*70)
    print("  TEST SUMMARY")
    print("="*70)
    
    passed = sum(1 for v in results.values() if v is True)
    total = len(results)
    
    print(f"\nPassed: {passed}/{total}")
    
    if passed == total:
        print("\n✓ ALL TESTS PASSED - Platinum Tier is ready!")
        print("\nPlatinum Demo Flow Verified:")
        print("  1. ✓ Cloud creates draft")
        print("  2. ✓ Draft syncs to Local")
        print("  3. ✓ Human approves (simulated)")
        print("  4. ✓ Local orchestrator executes")
        print("  5. ✓ Completion syncs to Cloud (audit)")
        print("  6. ✓ Security boundaries enforced")
        print("\nNext Steps:")
        print("  - Deploy Cloud VM using platinum/cloud_setup.sh")
        print("  - Configure Git sync between Cloud and Local")
        print("  - Test with real Gmail emails")
    else:
        print("\n⚠ SOME TESTS FAILED - Review the issues above")
    
    return results


def main():
    parser = argparse.ArgumentParser(description="Platinum Tier - Demo Flow Test")
    parser.add_argument(
        "--vault",
        default=str(Path(__file__).parent.parent / "AI_Employee_Vault"),
        help="Path to your Obsidian vault",
    )
    args = parser.parse_args()
    
    vault = Path(args.vault).resolve()
    if not vault.exists():
        print(f"ERROR: Vault not found at: {vault}")
        sys.exit(1)
    
    results = run_all_tests(vault)
    
    # Exit with error code if tests failed
    if not all(results.values()):
        sys.exit(1)
    
    sys.exit(0)


if __name__ == "__main__":
    main()
